config/routes.rb
Rails.application.routes.draw do



   #会員様
 scope module: 'public' do
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: "homes#top"
    get "about" => "homes#about"

    #検索ボタンが押された時、Searchesコントローラーのsearchアクションが実行されるように定義。
    #パス名は__「search_path」__
    get 'search' => 'searches#search'

    resources :spots, only: [:index]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'favorites' => 'customers#favorites'


    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :tags do
      get 'posts', to: 'posts#tag_search'
    end


 end



 #ゲストログイン
 devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end


  #管理者用

   devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: 'admin/sessions'
    }

  namespace :admin do
    get "/" => "homes#top"

    resources :customers, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :show, :destroy]

  end




end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_image

  enum status: {nonreleased: 0, released: 1}

  validates :customername, uniqueness: true, length: {minimum: 2, maximum: 15}
  validates :introduction, length: {maximum: 100}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/noimage.png')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  def self.guest
    find_or_create_by!(customername: 'guestcustomer', email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.customername = "guestcustomer"
    end
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @customer = Customer.where("customername LIKE?", "#{word}")
    elsif search == "forward_match"
      @customer = Customer.where("customername LIKE?","#{word}%")
    elsif search == "backward_match"
      @customer = Customer.where("customername LIKE?","%#{word}")
    elsif search == "partial_match"
      @customer = Customer.where("customername LIKE?","%#{word}%")
    else
      @customer = Customer.all
    end
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def destroy
    customer = Customer.find(params[:id])
    customer.destroy
    redirect_to admin_customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:customername, :introduction, :profile_image)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="mt-4 mb-4">ユーザー一覧</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr class="table-warning">
          <th>プロフィール画像</th>
          <th>ユーザーネーム</th>

        </tr>
      </thead>
      <% @customers.each do |customer| %>
      <tbody>
        <tr>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <%= image_tag customer.get_profile_image(50, 50), class: "rounded-circle" %>
            <% end %>
          </td>
          <td>
            <%= link_to admin_customer_path(customer) do %>
              <h5><%= customer.customername %></h5>
            <% end %>
          </td>

        </tr>
      </tbody>
      <% end %>
    </table>
    <div class="pagination justify-content-center"> <%= paginate @customers %></div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-4">
      <h3 class="mt-4 mb-4">プロフィール</h3>
      <div class="mb-3">
        <%= image_tag @customer.get_profile_image(200, 200), class: "rounded-circle" %>
      </div>
      <table class="table">
        <tbody>
          <tr>
            <th class="col-md-5">ユーザーネーム</th>
            <th><%= @customer.customername %></th>
          </tr>
          <tr>
            <th>自己紹介</th>
            <th><%= @customer.introduction %></th>
          </tr>

        </tbody>
      </table>
      <div class="row mt-4 mb-4">
        <%= link_to "ユーザーを削除する", admin_customer_path(@customer), method: :delete, data: { confirm: "ユーザーを削除してよろしいですか？" }, class: "btn btn-outline-danger rounded-pill" %>
      </div>
    </div>

    <div class="col-md-6 offset-sm-1">
      <h3 class="mt-4 mb-4">投稿履歴</h3>
      <table class="table table-hover table-inverse">
        <thead>
          <tr class="table-warning">
            <th>画像</th>
            <th>夜景スポット</th>
          </tr>
        </thead>
        <tbody>
          <% @customer.posts.each do |f| %>
          <tr>
            <td><%= image_tag f.get_spot_image(100, 100) %></td>
            <td><%= link_to f.title, admin_post_path(f) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>