config/routes.rb
Rails.application.routes.draw do



   #会員様
 scope module: 'public' do
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: "homes#top"
    get "about" => "homes#about"

    #検索ボタンが押された時、Searchesコントローラーのsearchアクションが実行されるように定義。
    #パス名は__「search_path」__
    get 'search' => 'searches#search'

    resources :spots, only: [:index]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'favorites' => 'customers#favorites'


    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :tags do
      get 'posts', to: 'posts#tag_search'
    end


 end



 #ゲストログイン
 devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end


  #管理者用

   devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: 'admin/sessions'
    }

  namespace :admin do
    get "/" => "homes#top"

    resources :customers, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :show, :destroy]

  end




end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
# before_action :authenticate_admin!

#   def index
#     @tags = Tag.all
#     @tag = Tag.page(params[:page]).per(10)
#   end

#   def destroy
#     tags = Tags.find(params[:id])
#     post.destroy
#     redirect_to admin_tags_path
#   end

#   private

  # def tag_params
  #   params.require(:tag).permit(:)
  # end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/tags/index.html.erb
<!--<div class="container">-->
<!--  <div class="row">-->
<!--    <h2 class="col-md-2 mt-4 mb-4">タグ一覧</h2>-->
<!--    <table class="table table-hover table-inverse">-->
<!--      <thead>-->
<!--        <tr class="table-warning">-->
<!--          <th>タグ</th>-->
<!--        </tr>-->
<!--      </thead>-->
<!--      < % @tag_list.each do |list| %>-->
<!--      <tbody>-->
<!--        <tr>-->
<!--          <td>-->
<!--            < %= link_to list.tag_name, tag_posts_path(tag_id: list.id) %>-->
<!--            < %= "(#{list.posts.count})" %>-->
<!--          </td>-->
<!--        </tr>-->
<!--      < % end %>-->

<!--      <h3 class="col-md-2 mt-4 md-4">タグ検索</h3>-->
<!--        < %= form_tag({controller:"posts",action:"index"}, method: :get) do %>-->
<!--          <div class="col-md-4 mt-4">-->
<!--            < %= text_field_tag :search %>-->
<!--            < %= submit_tag '検索', class: "btn btn-sm btn-warning"%>-->
<!--          </div>-->
<!--        < % end %>-->
<!--      </tbody>-->
<!--    </table>-->
<!--    <div class="pagination justify-content-center"> < %= paginate @tag %></div>-->
<!--  </div>-->
<!--</div>-->

app/views/admin/tags/show.html.erb
<!--<div class="container px-5 px-sm-0">-->
<!--  <div class="row">-->
<!--    <div class="col-md-4">-->
<!--      <h3 class="mt-4 mb-4">タグ</h3>-->
      
<!--      <table class="table">-->
<!--        <tbody>-->
<!--          <tr>-->
<!--            <th class="col-md-5">ユーザーネーム</th>-->
<!--            <th>< %= @customer.customername %></th>-->
<!--          </tr>-->
<!--          <tr>-->
<!--            <th>自己紹介</th>-->
<!--            <th>< %= @customer.introduction %></th>-->
<!--          </tr>-->

<!--        </tbody>-->
<!--      </table>-->
<!--      <div class="row mt-4 mb-4">-->
<!--        < %= link_to "タグを削除する", admin_tag_path(@tag), method: :delete, data: { confirm: "タグを削除してよろしいですか？" }, class: "btn btn-outline-danger rounded-pill" %>-->
<!--      </div>-->
<!--    </div>-->

<!--    <div class="col-md-6 offset-sm-1">-->
<!--      <h3 class="mt-4 mb-4">投稿履歴</h3>-->
<!--      <table class="table table-hover table-inverse">-->
<!--        <thead>-->
<!--          <tr class="table-warning">-->
<!--            <th>画像</th>-->
<!--            <th>夜景スポット</th>-->
<!--          </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--          < % @customer.posts.each do |f| %>-->
<!--          <tr>-->
<!--            <td>< %= image_tag f.get_spot_image(100, 100) %></td>-->
<!--            <td>< %= link_to f.title, admin_post_path(f) %></td>-->
<!--          </tr>-->
<!--          < % end %>-->
<!--        </tbody>-->
<!--      </table>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->