config/routes.rb
Rails.application.routes.draw do



   #会員様
 scope module: 'public' do
    devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
    }
    root to: "homes#top"
    get "about" => "homes#about"

    #検索ボタンが押された時、Searchesコントローラーのsearchアクションが実行されるように定義。
    #パス名は__「search_path」__
    get 'search' => 'searches#search'

    resources :spots, only: [:index]
    resources :customers, only: [:index, :show, :edit, :update] do
      get 'favorites' => 'customers#favorites'


    end
    resources :posts do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :tags do
      get 'posts', to: 'posts#tag_search'
    end


 end



 #ゲストログイン
 devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end


  #管理者用

   devise_for :admin, skip: [:registrations, :passwords], controllers: {
      sessions: 'admin/sessions'
    }

  namespace :admin do
    get "/" => "homes#top"

    resources :customers, only: [:index, :show, :destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :tags, only: [:index, :show, :destroy]

  end




end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= "#{obj.errors.count}件のエラーが発生しました" %></h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
 <div class="mx-auto">
  <strong><p class="notice text-center" style="color:green;"><%= flash[:notice] %></p></strong>
 </div>
<% elsif flash[:alert] %>
 <div class="mx-auto">
  <strong><p class="alert text-center" style="color:red;"><%= flash[:alert] %></p></strong>
 </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="margin-top: auto;">
  <div style="background-color: #391B9B;">
    <div class="row">
      <div class="mt-3 mb-3 mx-auto text-warning">
        <h5>@ChillOut_In_NightView</h5>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- ハンバーガーメニューアイコン -->

<div class="d-block d-md-none hum-icon">
  <i class="fas fa-bars fa-2x"></i>
</div>

<header style="background-color: #391B9B;">
  <div class="container">
    <div class="text-center m-2">
      <% if admin_signed_in? %>
        <%= link_to image_tag("logo.png"), admin_customers_path %>
      <% else %>
        <%= link_to image_tag("logo.png"), root_path %>
      <% end %>
    </div>

    <!-- パソコンでの画面表示 -->

    <div class="d-none d-md-block">
      <% if customer_signed_in? %>

        <!-- ユーザーがログインしている時 -->

        <div class="text-center">
          <ul class="list-inline">
            <li class="list-inline-item">
              <%= link_to customer_path(current_customer), class: "nav-link text-warning" do %>
                <i class="fas fa-user-cog"></i>マイページ
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to new_post_path, class: "nav-link text-warning" do %>
                <i class="fas fa-pencil-alt"></i>新規投稿
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to customers_path, class: "nav-link text-warning" do %>
                <i class="fas fa-user"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to posts_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>投稿一覧
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to tags_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>タグ一覧
               <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-warning" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>

        <!--管理者がログインしている時-->

        <div class="text-center">
          <ul class="list-inline">
            <li class="list-inline-item">
              <%= link_to admin_customers_path, class: "nav-link text-warning" do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to admin_posts_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>投稿一覧
              <% end %>
            </li>
            <!--<li class="list-inline-item">-->
            <!--  < %= link_to admin_tags_path, class: "nav-link text-warning" do %>-->
            <!--    <i class="fas fa-tag"></i>タグ一覧-->
            <!--  < % end %>-->
            <!--</li>-->
            <li class="list-inline-item">
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-warning" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>

        <!--ログインしていない時-->

        <div class="text-center">
          <ul class="list-inline">
             <li class="list-inline-item">
              <%= link_to about_path, class: "nav-link text-warning" do %>
                <i class="fab fa-readme"></i>アバウトページ
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to posts_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>投稿一覧
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to new_customer_registration_path, class: "nav-link text-warning" do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li class="list-inline-item">
              <%= link_to new_customer_session_path, class: "nav-link text-warning" do %>
                <i class="fas fa-user"></i>ログイン
              <% end %>
            </li>
             <li class="list-inline-item">
              <%= link_to customers_guest_sign_in_path,  class: "nav-link text-warning sign_in", method: :post  do %>
                <i class="fas fa-user-circle"></i>ゲストログイン

              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>

    <% if customer_signed_in? %>
      <div class="row mb-2">
        <div class="col-md-3 spots_search text-center">
          <%= link_to spots_path do %>
            <h5><i class="fas fa-search-location"></i>地図から探す</h5>
          <% end %>
        </div>

        <div class="col-md-9 search-box text-center">
          <%= render "public/searches/search" %>
        </div>
      </div>
    <% end %>
  </div>
</header>

<!-- スマートフォンでの画面表示 -->

<div class="d-none d-md-none vw-100 vh-100 hum-menu">
  <div class="w-100 h-100 d-flex flex-column justify-content-center align-items-center">
    <div class="container">
      <div class="text-center">
        <% if admin_signed_in? %>
          <%= link_to image_tag("logo.png"), admin_customers_path %>
        <% else %>
          <%= link_to image_tag("logo.png"), root_path %>
        <% end %>
      </div>

      <% if customer_signed_in? %>

        <!-- ユーザーがログインしている時 -->

        <div class="text-center mt-3">
          <ul class="list-unstyled">
            <li>
              <%= link_to customer_path(current_customer), class: "nav-link text-warning" do %>
                <i class="fas fa-user-cog"></i>マイページ
              <% end %>
            </li>
            <li>
              <%= link_to new_post_path, class: "nav-link text-warning" do %>
                <i class="fas fa-pencil-alt"></i>新規投稿
              <% end %>
            </li>
            <li>
              <%= link_to customers_path, class: "nav-link text-warning" do %>
                <i class="fas fa-users"></i>ユーザー一覧
              <% end %>
            </li>
            <li>
              <%= link_to posts_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to tags_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>タグ一覧
              <% end %>
            </li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete, class: "nav-link text-warningk" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      <% elsif admin_signed_in? %>

        <!--管理者がログインしている時-->

        <div class="text-center mt-3">
          <ul class="list-unstyled">
            <li>
            <%= link_to admin_customers_path, class: "nav-link text-warning" do %>
              <i class="fas fa-users"></i>ユーザー一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_posts_path, class: "nav-link text-warning" do %>
              <i class="fas fa-file-alt"></i>投稿一覧
            <% end %>
          </li>
          <!--<li>-->
          <!--  < %= link_to tags_path, class: "nav-link text-warning" do %>-->
          <!--    <i class="fas fa-tag"></i>タグ一覧-->
          <!--  < % end %>-->
          <!--</li>-->
          <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-warning" do %>
                <i class="fas fa-sign-out-alt"></i>ログアウト
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>

        <!--ログインしていない時-->

        <div class="text-center mt-3">
          <ul class="list-unstyled">
             <li>
              <%= link_to about_path, class: "nav-link text-warning" do %>
                <i class="fab fa-readme"></i>アバウトページ
              <% end %>
            </li>
            <li>
              <%= link_to posts_path, class: "nav-link text-warning" do %>
                <i class="fas fa-file-alt"></i>投稿一覧
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path, class: "nav-link text-warning" do %>
                <i class="fas fa-user-plus"></i>新規登録
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path, class: "nav-link text-warning" do %>
                <i class="fas fa-user"></i>ログイン
              <% end %>
            </li>
             <li>
              <%= link_to customers_guest_sign_in_path,  class: "nav-link text-warning sign_in", method: :post  do %>
                <i class="fas fa-user-circle"></i>ゲストログイン
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>

      <!-- ログインしている時の検索フォーム -->

      <% if customer_signed_in? %>
        <div class="row mb-2">
          <div class="col-md-3 spots_search text-center ">
            <%= link_to spots_path do %>
              <h5><i class="fas fa-search-location text-warning"></i>地図から探す</h5>
            <% end %>
          </div>

          <div class="col-md-9 search-box text-center ">
            <%= render "public/searches/search" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChillOutInNightview</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&display=swap" rel="stylesheet">

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application'%>
  </head>

  <body style="display: flex;flex-direction: column;min-height: 100vh;">
     <%= render "layouts/header" %>
    <%= flash[:notice] %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>